version: '3'

networks:
  backend:

services:
  calculajuros:
    build:
      context: ./FinTech.CalculaJuros.Api
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 7000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  taxajuros:
    build:
      context: ./FinTech.TaxaJuros.Api
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 7500:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
